### ISSUE TITLE
Aviso anticipado para mecánicos in out

### ISSUE THREAD

**Issue by Aki62** [emilia-s2/Guia-DG-Portugues#2]
Hola, sería bueno si la guía puede decir dónde colocarse antes durante la magia roja/mecánica de pizza en AANM/AAHM/DAHM, es decir: de adentro hacia afuera, de afuera hacia adentro. Gracias. (Google Translate)

**Comment by emilia-s2** [comment]
I'll check what can be done, and if possible I'll do it...

**Comment by Aki62** [comment]
I appreciate your quick response. Thank you!

**Comment by emilia-s2** [comment]
I tried to do what I could with the little time I have, I even got some results, but not good enough, so I will discard it, this is not something very simple to do, some mechanics are impossible to apply this anticipation function, I feel much!

**Comment by Aki62** [comment]
I see, don't overwork yourself. This is just a request. I thank you for the efforts you put into polishing this module. Godspeed.
